# Generated by Django 4.2.4 on 2023-08-29 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_employee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='colaboradores',
            name='beneficios',
        ),
        migrations.RemoveField(
            model_name='colaboradores',
            name='encargos',
        ),
        migrations.RemoveField(
            model_name='colaboradores',
            name='salario',
        ),
        migrations.AddField(
            model_name='cargos',
            name='salario',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
