# Generated by Django 4.2.4 on 2023-08-29 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_remove_colaboradores_beneficios_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='colaboradores',
            old_name='cargo',
            new_name='cargo_id',
        ),
    ]
