# Generated by Django 4.2.4 on 2023-08-29 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_rename_cargo_colaboradores_cargo_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='colaboradores',
            old_name='cargo_id',
            new_name='cargo',
        ),
    ]
