# Generated by Django 4.2.4 on 2023-08-29 22:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_rename_cargo_id_colaboradores_cargo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='colaborador',
        ),
        migrations.AlterField(
            model_name='employee',
            name='cargo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.cargos'),
        ),
    ]
