# Generated by Django 4.2.4 on 2023-08-29 22:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_employee_colaborador'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='cargofk',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dashboard.cargos'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employee',
            name='cargo',
            field=models.CharField(choices=[('Auxiliar', 'Auxiliar'), ('Assistente Técnico', 'Assistente Técnico'), ('Técnico N1', 'Técnico N1'), ('Técnico N2', 'Técnico N2'), ('Técnico N3', 'Técnico N3'), ('Coordenador', 'Coordenador'), ('Gerente', 'Gerente'), ('Diretor', 'Diretor')], max_length=50),
        ),
    ]
