# Generated by Django 4.2.4 on 2023-08-29 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_employee_cargofk_alter_employee_cargo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='cargo',
        ),
    ]
