# Generated by Django 4.2.4 on 2023-08-29 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_remove_employee_cargo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='cargofk',
            new_name='cargo',
        ),
    ]
