# Generated by Django 4.2.4 on 2023-08-30 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_rename_cargofk_employee_cargo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='cargo',
            new_name='cargos',
        ),
    ]
