# Generated by Django 4.2.4 on 2023-08-30 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0017_rename_cargo_employee_cargos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='cargos',
            new_name='cargo',
        ),
    ]
