# Generated by Django 4.2.4 on 2023-09-03 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0019_employee_custo_salario'),
    ]

    operations = [
        migrations.AddField(
            model_name='gastosfixos',
            name='ano',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gastosfixos',
            name='mes',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gastosfixos',
            name='tipo',
            field=models.CharField(default=1, max_length=12),
            preserve_default=False,
        ),
    ]
