# Generated by Django 4.2.4 on 2023-09-06 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0020_gastosfixos_ano_gastosfixos_mes_gastosfixos_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuxiliarCalculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_salarios_gestores', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_salarios_prestadores', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_prestadores', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Beneficios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=100)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mes', models.PositiveIntegerField()),
                ('ano', models.PositiveIntegerField()),
            ],
        ),
    ]
