# Generated by Django 4.2.4 on 2023-09-06 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0021_auxiliarcalculo_beneficios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auxiliarcalculo',
            name='total_prestadores',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='auxiliarcalculo',
            name='total_salarios_gestores',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='auxiliarcalculo',
            name='total_salarios_prestadores',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
