# Generated by Django 4.2.4 on 2023-09-06 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0022_alter_auxiliarcalculo_total_prestadores_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auxiliarcalculo',
            name='total_gastos_condominio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='auxiliarcalculo',
            name='total_meses_condominio',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
