# Generated by Django 4.2.4 on 2023-09-06 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0023_auxiliarcalculo_total_gastos_condominio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auxiliarcalculo',
            name='total_meses_horas',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
