# Generated by Django 4.2.4 on 2023-09-06 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0024_auxiliarcalculo_total_meses_horas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auxiliarcalculo',
            name='total_gastos_condominio',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
        ),
        migrations.AlterField(
            model_name='auxiliarcalculo',
            name='total_meses_condominio',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='auxiliarcalculo',
            name='total_meses_horas',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='auxiliarcalculo',
            name='total_prestadores',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='auxiliarcalculo',
            name='total_salarios_gestores',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
        ),
        migrations.AlterField(
            model_name='auxiliarcalculo',
            name='total_salarios_prestadores',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
        ),
    ]
