# Generated by Django 4.2.4 on 2023-09-06 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0026_alter_auxiliarcalculo_total_gastos_condominio_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auxiliarcalculo',
            old_name='total_meses_horas',
            new_name='total_meses_calendario',
        ),
        migrations.AddField(
            model_name='auxiliarcalculo',
            name='total_meses_horasprodutivas',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
