# Generated by Django 4.2.4 on 2023-09-07 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0028_remove_beneficios_ano_remove_beneficios_mes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='beneficios',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
