# Generated by Django 4.2.4 on 2023-09-07 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0029_employee_beneficios'),
    ]

    operations = [
        migrations.AddField(
            model_name='colaboradores',
            name='setor',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
