# Generated by Django 4.2.4 on 2023-09-08 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0030_colaboradores_setor'),
    ]

    operations = [
        migrations.AddField(
            model_name='auxiliarcalculo',
            name='destinatario_email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
    ]
