# Generated by Django 4.2.4 on 2023-09-09 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0031_auxiliarcalculo_destinatario_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='colaboradores',
            name='cargo',
        ),
    ]
