# Generated by Django 4.2.4 on 2023-09-12 23:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0032_remove_colaboradores_cargo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rubrica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tributos', models.DecimalField(decimal_places=2, max_digits=10)),
                ('compra_materiais', models.DecimalField(decimal_places=2, max_digits=10)),
                ('materiais_dvs', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dvs_socio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('beneficios', models.DecimalField(decimal_places=2, max_digits=10)),
                ('telefonia_comunicacao', models.DecimalField(decimal_places=2, max_digits=10)),
                ('seguro_maquinas_equipamentos', models.DecimalField(decimal_places=2, max_digits=10)),
                ('manutencao', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dvs_operacao', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bonus_resultado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('plr', models.DecimalField(decimal_places=2, max_digits=10)),
                ('horas_extras', models.DecimalField(decimal_places=2, max_digits=10)),
                ('exames_adiciona_demissional', models.DecimalField(decimal_places=2, max_digits=10)),
                ('terceirizados', models.DecimalField(decimal_places=2, max_digits=10)),
                ('alimentacao', models.DecimalField(decimal_places=2, max_digits=10)),
                ('hospedagem', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quilometragem', models.DecimalField(decimal_places=2, max_digits=10)),
                ('deslocamento', models.DecimalField(decimal_places=2, max_digits=10)),
                ('combistivel', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estacionamento_pegadgio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('comissoes', models.DecimalField(decimal_places=2, max_digits=10)),
                ('seguros_obra_dvs', models.DecimalField(decimal_places=2, max_digits=10)),
                ('manutencao_conservacao', models.DecimalField(decimal_places=2, max_digits=10)),
                ('distrato_multas', models.DecimalField(decimal_places=2, max_digits=10)),
                ('auxiliarcalculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.auxiliarcalculo')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rubricas_colaborador', to='dashboard.colaboradores')),
                ('insumos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.insumos')),
            ],
        ),
        migrations.CreateModel(
            name='DescricaoObra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horas', models.CharField(max_length=100)),
                ('quantidade', models.PositiveIntegerField(default=0)),
                ('orcamento_id', models.PositiveIntegerField(default=0)),
                ('custo_mod', models.CharField(max_length=100)),
                ('custo_hora_con', models.CharField(max_length=100)),
                ('custo_total', models.CharField(max_length=100)),
                ('auxiliarcalculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.auxiliarcalculo')),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.cargos')),
            ],
        ),
    ]
