# Generated by Django 4.2.4 on 2023-09-15 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0033_rubrica_descricaoobra'),
    ]

    operations = [
        migrations.AddField(
            model_name='descricaoobra',
            name='horas_produtivas',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
