# Generated by Django 4.2.4 on 2023-09-15 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0034_descricaoobra_horas_produtivas'),
    ]

    operations = [
        migrations.AddField(
            model_name='descricaoobra',
            name='total_condominio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='descricaoobra',
            name='total_custo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='descricaoobra',
            name='total_mod',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
