# Generated by Django 4.2.4 on 2023-09-16 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0035_descricaoobra_total_condominio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rubrica',
            name='orcamento_id',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
