# Generated by Django 4.2.4 on 2023-09-16 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0036_rubrica_orcamento_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beneficios',
            name='funcionario',
        ),
        migrations.AddField(
            model_name='beneficios',
            name='cargo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dashboard.cargos'),
            preserve_default=False,
        ),
    ]
