# Generated by Django 4.2.4 on 2023-09-17 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0038_alter_descricaoobra_orcamento_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rubrica',
            old_name='combistivel',
            new_name='combustivel',
        ),
        migrations.RenameField(
            model_name='rubrica',
            old_name='estacionamento_pegadgio',
            new_name='condominio',
        ),
        migrations.RemoveField(
            model_name='rubrica',
            name='auxiliarcalculo',
        ),
        migrations.RemoveField(
            model_name='rubrica',
            name='funcionario',
        ),
        migrations.AddField(
            model_name='rubrica',
            name='custo_hora',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rubrica',
            name='estacionamento_pedagio',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rubrica',
            name='lucros',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rubrica',
            name='quantidade',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='rubrica',
            name='insumos',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='rubrica',
            name='tributos',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
