# Generated by Django 4.2.4 on 2023-09-19 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0042_alter_descricaoobra_custo_hora_con_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendariomensal',
            name='dias_uteis',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='descricaoobra',
            name='horas',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
