# Generated by Django 4.2.4 on 2023-09-19 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0043_alter_calendariomensal_dias_uteis_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendariomensal',
            name='feriado',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
