# Generated by Django 4.2.4 on 2023-09-21 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0044_calendariomensal_feriado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendariomensal',
            name='feriado',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
