# Generated by Django 4.2.4 on 2023-09-22 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0045_alter_calendariomensal_feriado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calendariomensal',
            name='funcionario',
        ),
        migrations.RemoveField(
            model_name='calendariomensal',
            name='mes',
        ),
        migrations.AddField(
            model_name='calendariomensal',
            name='descricao',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
