# Generated by Django 4.2.4 on 2023-09-22 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0047_calendariomensal_mes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendariomensal',
            name='jornada_diaria',
            field=models.PositiveIntegerField(),
        ),
    ]
