# Generated by Django 4.2.4 on 2023-09-23 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0048_alter_calendariomensal_jornada_diaria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rubrica',
            name='alimentacao',
        ),
        migrations.RemoveField(
            model_name='rubrica',
            name='bonus_resultado',
        ),
        migrations.RemoveField(
            model_name='rubrica',
            name='combustivel',
        ),
        migrations.RemoveField(
            model_name='rubrica',
            name='comissoes',
        ),
        migrations.RemoveField(
            model_name='rubrica',
            name='compra_materiais',
        ),
        migrations.RemoveField(
            model_name='rubrica',
            name='deslocamento',
        ),
        migrations.RemoveField(
            model_name='rubrica',
            name='distrato_multas',
        ),
        migrations.RemoveField(
            model_name='rubrica',
            name='dvs_operacao',
        ),
        migrations.RemoveField(
            model_name='rubrica',
            name='dvs_socio',
        ),
        migrations.RemoveField(
            model_name='rubrica',
            name='estacionamento_pedagio',
        ),
        migrations.RemoveField(
            model_name='rubrica',
            name='exames_adiciona_demissional',
        ),
        migrations.RemoveField(
            model_name='rubrica',
            name='horas_extras',
        ),
        migrations.RemoveField(
            model_name='rubrica',
            name='hospedagem',
        ),
        migrations.RemoveField(
            model_name='rubrica',
            name='insumos',
        ),
        migrations.RemoveField(
            model_name='rubrica',
            name='manutencao',
        ),
        migrations.RemoveField(
            model_name='rubrica',
            name='manutencao_conservacao',
        ),
        migrations.RemoveField(
            model_name='rubrica',
            name='materiais_dvs',
        ),
        migrations.RemoveField(
            model_name='rubrica',
            name='plr',
        ),
        migrations.RemoveField(
            model_name='rubrica',
            name='quilometragem',
        ),
        migrations.RemoveField(
            model_name='rubrica',
            name='seguro_maquinas_equipamentos',
        ),
        migrations.RemoveField(
            model_name='rubrica',
            name='seguros_obra_dvs',
        ),
        migrations.RemoveField(
            model_name='rubrica',
            name='telefonia_comunicacao',
        ),
        migrations.RemoveField(
            model_name='rubrica',
            name='terceirizados',
        ),
        migrations.AddField(
            model_name='rubrica',
            name='capacidade_produtiva',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rubrica',
            name='outros',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
