# Generated by Django 4.2.4 on 2023-09-23 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0050_despesasdinamicas_remove_gastosvariaveis_insumo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='despesasdinamicas',
            old_name='rubrica_id',
            new_name='rubrica',
        ),
    ]
