# Generated by Django 4.2.4 on 2023-09-25 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0051_rename_rubrica_id_despesasdinamicas_rubrica'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendariomensal',
            name='dias_uteis',
            field=models.DecimalField(decimal_places=6, max_digits=12),
        ),
    ]
