# Generated by Django 4.2.4 on 2023-09-29 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0054_alter_auxiliarcalculo_total_meses_horasprodutivas'),
    ]

    operations = [
        migrations.AddField(
            model_name='rubrica',
            name='cliente',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
