# Generated by Django 4.2.4 on 2023-10-11 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0055_rubrica_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='rubrica',
            name='valor_lucro',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='rubrica',
            name='valor_outros',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='rubrica',
            name='valor_tributos',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
