# Generated by Django 4.2.4 on 2023-10-17 00:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0056_rubrica_valor_lucro_rubrica_valor_outros_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargos',
            name='usuario_admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cargos', to=settings.AUTH_USER_MODEL),
        ),
    ]
