# Generated by Django 4.2.4 on 2023-10-19 21:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0056_rubrica_valor_lucro_rubrica_valor_outros_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auxiliarcalculo',
            name='empresa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dashboard.empresa'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='beneficios',
            name='empresa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dashboard.empresa'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='calendariomensal',
            name='empresa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dashboard.empresa'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cargos',
            name='empresa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dashboard.empresa'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='colaboradores',
            name='empresa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dashboard.empresa'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='descricaoobra',
            name='empresa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dashboard.empresa'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='despesasdinamicas',
            name='empresa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dashboard.empresa'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='empresa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dashboard.empresa'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gastosfixos',
            name='empresa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dashboard.empresa'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gastosvariaveis',
            name='empresa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dashboard.empresa'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='horasprodutivas',
            name='empresa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dashboard.empresa'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='propostas',
            name='empresa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dashboard.empresa'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rubrica',
            name='empresa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dashboard.empresa'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuarios',
            name='empresa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dashboard.empresa'),
            preserve_default=False,
        ),
    ]
