# Generated by Django 4.2.4 on 2023-10-19 23:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0058_empresa_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auxiliarcalculo',
            name='empresa',
        ),
        migrations.RemoveField(
            model_name='gastosfixos',
            name='empresa',
        ),
        migrations.RemoveField(
            model_name='horasprodutivas',
            name='empresa',
        ),
        migrations.RemoveField(
            model_name='usuarios',
            name='empresa',
        ),
        migrations.AddField(
            model_name='endereco',
            name='empresa_endereco',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='enderecos', to='dashboard.empresa'),
            preserve_default=False,
        ),
    ]
