# Generated by Django 4.2.4 on 2023-10-20 00:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0059_remove_auxiliarcalculo_empresa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gastosfixos',
            name='empresa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dashboard.empresa'),
            preserve_default=False,
        ),
    ]
