# Generated by Django 4.2.4 on 2023-10-24 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0058_remove_cargos_usuario_admin'),
        ('dashboard', '0060_gastosfixos_empresa'),
    ]

    operations = [
    ]
