# Generated by Django 4.2.4 on 2023-11-12 00:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0062_remove_beneficios_empresa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargos',
            name='empresa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dashboard.empresa'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='endereco',
            name='empresa_endereco',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='enderecos', to='dashboard.empresa'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuarios',
            name='empresa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dashboard.empresa'),
            preserve_default=False,
        ),
    ]
