# Generated by Django 4.2.4 on 2023-11-12 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0063_cargos_empresa_endereco_empresa_endereco_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cargos',
            name='empresa',
        ),
        migrations.RemoveField(
            model_name='endereco',
            name='empresa_endereco',
        ),
        migrations.RemoveField(
            model_name='usuarios',
            name='empresa',
        ),
    ]
